language: node_js
sudo: required
dist: trusty
node_js:  
  - "9"

matrix:
  include:
  - os: linux
  - os: osx

cache:
  directories:
    - node_modules

install:
  - npm install
  - cd app/src/main/server
  - npm install
  - cd ../../../..
  
script:
  - npm run build